// /cache/* — public read-only cache snapshot.
//
// The gateway is read-only by design. This module preserves that:
// peers can DOWNLOAD a snapshot of the cache to bootstrap a cold
// gateway, but no one (including the operator) writes to the cache
// over HTTP. Bootstrap is a filesystem operation on the operator's
// own machine before/while the gateway runs.
//
// Snapshot format: tar.gz of CACHE_DIR with a VACUUM-INTO consistent
// cache.db plus all blob subdirectories. Recipient untars into their
// CACHE_DIR and starts/restarts their gateway.

import { Hono } from "hono";
import { Database } from "bun:sqlite";
import { join } from "node:path";
import { existsSync } from "node:fs";

const CACHE_DIR = process.env.CACHE_DIR || "./cache";

export const cacheRouter = new Hono();

function dbPath(): string {
  return join(CACHE_DIR, "cache.db");
}

async function runShell(script: string): Promise<{ exitCode: number; stderr: string }> {
  const proc = Bun.spawn(["sh", "-c", script], { stdout: "pipe", stderr: "pipe" });
  const exitCode = await proc.exited;
  const stderr = exitCode === 0 ? "" : await new Response(proc.stderr).text();
  return { exitCode, stderr };
}

cacheRouter.get("/info", (c) => {
  const p = dbPath();
  if (!existsSync(p)) return c.json({ entries: 0, totalSize: 0, byType: {}, cacheDir: CACHE_DIR });
  const db = new Database(p, { readonly: true });
  const total = db.query<{ n: number; bytes: number }, []>(
    "SELECT COUNT(*) AS n, COALESCE(SUM(size), 0) AS bytes FROM cache_entries",
  ).get();
  const byType: Record<string, { entries: number; bytes: number }> = {};
  for (const row of db.query<{ type: string; n: number; bytes: number }, []>(
    "SELECT type, COUNT(*) AS n, COALESCE(SUM(size), 0) AS bytes FROM cache_entries GROUP BY type ORDER BY n DESC",
  ).all()) {
    byType[row.type] = { entries: row.n, bytes: row.bytes };
  }
  db.close();
  return c.json({
    entries: total?.n ?? 0,
    totalSize: total?.bytes ?? 0,
    byType,
    cacheDir: CACHE_DIR,
  });
});

cacheRouter.get("/snapshot", async (c) => {
  const tag = `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
  const stage = `/tmp/cache-snapshot-${tag}`;
  const tarPath = `/tmp/cache-snapshot-${tag}.tar.gz`;

  // Stage every cache subdir / blob file. Skip the live cache.db and
  // its WAL/SHM journals — we'll write a fresh consistent cache.db via
  // VACUUM INTO so the recipient sqlite opens cleanly.
  const setup = await runShell([
    "set -e",
    `mkdir -p ${stage}`,
    `cd ${CACHE_DIR}`,
    `find . -mindepth 1 -maxdepth 1 -not -name 'cache.db' -not -name 'cache.db-shm' -not -name 'cache.db-wal' -exec cp -r {} ${stage}/ \\;`,
  ].join(" && "));
  if (setup.exitCode !== 0) {
    await runShell(`rm -rf ${stage}`);
    return c.json({ error: "snapshot setup failed", stderr: setup.stderr }, 500);
  }

  const liveDb = dbPath();
  if (existsSync(liveDb)) {
    try {
      const db = new Database(liveDb, { readonly: true });
      // bun:sqlite does not bind path as a parameter for VACUUM. Inline
      // with single-quote escaping (the path is generated by us and
      // contains no quotes anyway, but escape defensively).
      const stageDb = join(stage, "cache.db").replace(/'/g, "''");
      db.run(`VACUUM INTO '${stageDb}'`);
      db.close();
    } catch (e) {
      console.error("[cache] VACUUM INTO failed, copying live db as-is:", e);
      await runShell(`cp ${liveDb} ${join(stage, "cache.db")}`);
    }
  }

  const tar = await runShell(`cd ${stage} && tar -czf ${tarPath} . && rm -rf ${stage}`);
  if (tar.exitCode !== 0) {
    await runShell(`rm -rf ${stage} ${tarPath}`);
    return c.json({ error: "tar failed", stderr: tar.stderr }, 500);
  }

  const blob = Bun.file(tarPath);
  const stream = new ReadableStream({
    async start(controller) {
      const reader = blob.stream().getReader();
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        controller.enqueue(value);
      }
      controller.close();
      await runShell(`rm -f ${tarPath}`);
    },
  });

  return new Response(stream, {
    headers: {
      "content-type": "application/gzip",
      "content-disposition": 'attachment; filename="cache-snapshot.tar.gz"',
      "x-cache-snapshot-version": "1",
    },
  });
});
